# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'CSC690Final' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'Alamofire'
  pod 'Hue'
  
  # Pods for CSC690Final

  target 'CSC690FinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CSC690FinalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
